apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: istio-system
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: istio-poc-rr.example.com.
    # Enable use of manually pre-defined global static IP
    # Enable use of a GCP-managed certificate through a ManagedCertificate resource
    networking.gke.io/managed-certificates: ingress-certificate
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: istio-ingressgateway
          servicePort: 80
    